<%
sub RegistraNumeroSerie(prCOD_EVENTO,prCOD_INSCRICAO,prCOD_PROD,prDT_COMPRA,prCOD_STATUS_PRECO)
Dim strSQL, objRS
  strSQL = "SELECT * FROM TBL_CONTROLE_SERIE WHERE COD_EVENTO = " & prCOD_EVENTO & " AND COD_INSCRICAO = " & prCOD_INSCRICAO & " AND COD_PROD = " & prCOD_PROD & " AND COD_STATUS_PRECO = " & prCOD_STATUS_PRECO
  Set objRS = objConn.Execute(strSQL)
  If not objRS.EOF Then
    strSQL = "UPDATE TBL_CONTROLE_SERIE SET DT_REIMPRESSAO = NOW() WHERE COD_EVENTO = " & prCOD_EVENTO & " AND COD_INSCRICAO = " & prCOD_INSCRICAO & " AND COD_PROD = " & prCOD_PROD & " AND COD_STATUS_PRECO = " & prCOD_STATUS_PRECO
	objConn.Execute(strSQL)
  Else
    strSQL = "INSERT INTO TBL_CONTROLE_SERIE (COD_EVENTO, COD_INSCRICAO, DT_COMPRA, NRO_SERIE, DT_IMPRESSAO, COD_PROD, COD_STATUS_PRECO) VALUES (" & prCOD_EVENTO & "," & prCOD_INSCRICAO & ",'" & PrepDataIve(prDT_COMPRA,False,True) & "',GET_NRO_SERIE(" & prCOD_EVENTO & "," & prCOD_PROD & "," & prCOD_STATUS_PRECO & "), NOW()," & prCOD_PROD & "," & prCOD_STATUS_PRECO & ")"
	objConn.Execute(strSQL)
  End If
  FechaRecordSet objRS
end sub
%>