<%@ LANGUAGE=vbscript %>
<% Option Explicit %>
<% Response.Expires = 0 %>
<!--#include file="../_database/ADOVBS.INC"--> 
<!--#include file="../_database/config.inc"-->
<!--#include file="../_database/athdbConn.asp"-->
<!--#include file="../_database/athUtils.asp"-->
<!--#include file="../_include/barcode39.asp" -->
<%
Function intToSQL(pr_VALOR)
  If pr_VALOR&"" = "" or not isnumeric(pr_VALOR) Then
    intToSQL = "NULL"
  Else
    intToSQL = pr_VALOR
  End If
End Function

Dim strSQL, objRS, ObjConn, objRSAux, objRSDetail
Dim strCOD_EVENTO, strTITULO_EVENTO, strCOD_EVENTO_ORIGEM

AbreDBConn objConn, CFG_DB_DADOS

strCOD_EVENTO = Request("COD_EVENTO")
strCOD_EVENTO_ORIGEM = Request("COD_EVENTO_ORIGEM")
strTITULO_EVENTO = Request("TITULO")

If strCOD_EVENTO_ORIGEM = "" Then
  strCOD_EVENTO_ORIGEM = Session("COD_EVENTO")
End If

If strCOD_EVENTO = "" Then
  strCOD_EVENTO = 0
End If
%>
<html>
<head>
<title>ProEvento <%=Session("NOME_EVENTO")%> </title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link href="../_css/csm.css" rel="stylesheet" type="text/css">
<script language="JavaScript">
<!--
//-->
</script>
</head>
<body bgcolor="#FFFFFF" background="../img/bg_dialog.gif" text="#000000" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<%	
strSQL =  "SELECT * FROM TBL_EVENTO WHERE COD_EVENTO = " & strCOD_EVENTO
Set objRS = objConn.Execute(strSQL)
If not objRS.EOF Then
  strCOD_EVENTO = 0
End If
FechaRecordSet objRS

If strCOD_EVENTO = 0 Then
	strSQL =  "SELECT MAX(COD_EVENTO) as PROX_EVENTO FROM TBL_EVENTO WHERE COD_EVENTO <> 999 "
	Set objRS = objConn.Execute(strSQL)
	If not objRS.EOF Then
	  strCOD_EVENTO = objRS("PROX_EVENTO")
	End If
	FechaRecordSet objRS
	If strCOD_EVENTO&"" = "" Then
	  strCOD_EVENTO = 0
	End If
	strCOD_EVENTO = strCOD_EVENTO + 1
End If


If Ucase(Request("acao")) = "COPIAR" Then
%>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
 <tr>
  <td>
<%
	
	'If strCOD_EVENTO = "" Then
	'  strCOD_EVENTO = objRS("COD_EVENTO")
	'End If
	
strSQL = "INSERT INTO TBL_EVENTO (COD_EVENTO, NOME, NOME_COMPLETO, CABECALHO, RODAPE, SITE, DT_MATERIAL, HR_MATERIAL, PAVILHAO, CIDADE, AGENCIA_TURISMO, AGENCIA_PUBLICIDADE, AGENCIA_BANCARIA, MONTADORA, DT_INICIO, DT_FIM, ESTADO_EVENTO, LOGOMARCA, EMAIL_SENDER, HORA_INICIO, HORA_FIM, FREE, LOJA_STATUS_PRECO, STATUS_PRECO, STATUS_CRED, EMAIL, SYS_INATIVO, ATIVO, CABECALHO_LOJA, RODAPE_LOJA, INSTRUCAO_INSC_EXISTENTE, ARIEL_TEXTO, ARIEL_TEXTO_INTL, ARIEL_TEXTO_NPG, ARM_TEXTO, ARM_TEXTO_INTL, ACE_TEXTO, ACE_TEXTO_INTL, ACEPRESS_TEXTO, ACEPRESS_TEXTO_INTL, MOD1_TITLE, MOD1_TEXTO, MOD2_TITLE, MOD2_TEXTO, MOD3_TITLE, MOD3_TEXTO, MOD4_TITLE, MOD4_TEXTO, MOD5_TITLE, MOD5_TEXTO, MOD6_TITLE, MOD6_TEXTO, MOD7_TITLE, MOD7_TEXTO, FONE, LOJA_ATIVA, LOJAPJ_ATIVA, MODELO_LOJAPJ, IDUSER_LOJA, RECIBO_TEXTO, CNPJ, COD_MOEDA_EVENTO, COD_MOEDA_COBRANCA, COD_MOEDA_REFERENCIA, LOJA_SHOW_DADOS, LOJA_SHOW_ENTIDADE, ATESTADO_TEXTO, ACE_TEXTO_US, ACE_TEXTO_SP, ACE_ASSUNTO, ACE_ASSUNTO_US, ACE_ASSUNTO_SP, ACE_ASSUNTO_INTL, LOJA_SHOW_FINANCEIRO, LOJA_SHOW_FATURAMENTO, STATUS_PRECO_VISITANTE, CABECALHO_PAPER, RODAPE_PAPER, EMAIL_AUDITORIA, EMAIL_AUDITORIA_INTL, CONVITE_TEXTO, CONVITE_VIP_TEXTO, CONVITE_ELETRONICO_TEXTO, CONVITE_ELETRONICO_TEXTO_INTL, CABECALHO_RECIBO, SUBPAPER_ATIVA, ARM_ASSUNTO, ARM_ASSUNTO_INTL, APE_TEXTO, APE_ASSUNTO, APE_TEXTO_INTL, APE_ASSUNTO_INTL, PSC_ATIVA, COD_GRUPO_EVENTO, MOD8_TITLE, MOD8_TEXTO, MOD9_TITLE, MOD9_TEXTO, MOD10_TITLE, MOD10_TEXTO, SMS_USER, SMS_PWD, SMS_TEXTO, PSC_STATUS_CRED, CUPOM_FISCAL, VENDA_RAPIDA, RETIRADA_MATERIAL, LIMITE_IDADE, SMTP_SERVER, SMTP_USER, SMTP_PWD, INSCR_MUNICIPAL, ENTIDADE_OBRIGATORIO, CERTIFICADO_TEXTO1, CERTIFICADO_TEXTO2, ACEPRESS_TEXTO_US, ACEPRESS_TEXTO_ES, EMAIL_PRESS)"
strSQL = strSQL & " SELECT "&strCOD_EVENTO&", if('"&strTITULO_EVENTO&"'='',NOME,'"&strTITULO_EVENTO&"'), if('"&strTITULO_EVENTO&"'='',NOME_COMPLETO,'"&strTITULO_EVENTO&"'), CABECALHO, RODAPE, SITE, DT_MATERIAL, HR_MATERIAL, PAVILHAO, CIDADE, AGENCIA_TURISMO, AGENCIA_PUBLICIDADE, AGENCIA_BANCARIA, MONTADORA, DT_INICIO, DT_FIM, ESTADO_EVENTO, LOGOMARCA, EMAIL_SENDER, HORA_INICIO, HORA_FIM, FREE, LOJA_STATUS_PRECO, STATUS_PRECO, STATUS_CRED, EMAIL, SYS_INATIVO, ATIVO, CABECALHO_LOJA, RODAPE_LOJA, INSTRUCAO_INSC_EXISTENTE, ARIEL_TEXTO, ARIEL_TEXTO_INTL, ARIEL_TEXTO_NPG, ARM_TEXTO, ARM_TEXTO_INTL, ACE_TEXTO, ACE_TEXTO_INTL, ACEPRESS_TEXTO, ACEPRESS_TEXTO_INTL, MOD1_TITLE, MOD1_TEXTO, MOD2_TITLE, MOD2_TEXTO, MOD3_TITLE, MOD3_TEXTO, MOD4_TITLE, MOD4_TEXTO, MOD5_TITLE, MOD5_TEXTO, MOD6_TITLE, MOD6_TEXTO, MOD7_TITLE, MOD7_TEXTO, FONE, LOJA_ATIVA, LOJAPJ_ATIVA, MODELO_LOJAPJ, IDUSER_LOJA, RECIBO_TEXTO, CNPJ, COD_MOEDA_EVENTO, COD_MOEDA_COBRANCA, COD_MOEDA_REFERENCIA, LOJA_SHOW_DADOS, LOJA_SHOW_ENTIDADE, ATESTADO_TEXTO, ACE_TEXTO_US, ACE_TEXTO_SP, ACE_ASSUNTO, ACE_ASSUNTO_US, ACE_ASSUNTO_SP, ACE_ASSUNTO_INTL, LOJA_SHOW_FINANCEIRO, LOJA_SHOW_FATURAMENTO, STATUS_PRECO_VISITANTE, CABECALHO_PAPER, RODAPE_PAPER, EMAIL_AUDITORIA, EMAIL_AUDITORIA_INTL, CONVITE_TEXTO, CONVITE_VIP_TEXTO, CONVITE_ELETRONICO_TEXTO, CONVITE_ELETRONICO_TEXTO_INTL, CABECALHO_RECIBO, SUBPAPER_ATIVA, ARM_ASSUNTO, ARM_ASSUNTO_INTL, APE_TEXTO, APE_ASSUNTO, APE_TEXTO_INTL, APE_ASSUNTO_INTL, PSC_ATIVA, COD_GRUPO_EVENTO, MOD8_TITLE, MOD8_TEXTO, MOD9_TITLE, MOD9_TEXTO, MOD10_TITLE, MOD10_TEXTO, SMS_USER, SMS_PWD, SMS_TEXTO, PSC_STATUS_CRED, CUPOM_FISCAL, VENDA_RAPIDA, RETIRADA_MATERIAL, LIMITE_IDADE, SMTP_SERVER, SMTP_USER, SMTP_PWD, INSCR_MUNICIPAL, ENTIDADE_OBRIGATORIO, CERTIFICADO_TEXTO1, CERTIFICADO_TEXTO2, ACEPRESS_TEXTO_US, ACEPRESS_TEXTO_ES, EMAIL_PRESS FROM TBL_EVENTO WHERE COD_EVENTO = " & strCOD_EVENTO_ORIGEM

objConn.Execute(strSQL)

%>
- Evento: <%=strTITULO_EVENTO%><br>
<br>
<%

	
Dim objRSProd, strCOD_PROD

strSQL = "SELECT * FROM TBL_PRODUTOS WHERE COD_EVENTO = " & strCOD_EVENTO_ORIGEM
Set objRSProd = objConn.Execute(strSQL)
Do While not objRSProd.EOF 
  
  strSQL = "SELECT MAX(COD_PROD) AS LAST_PROD FROM TBL_PRODUTOS"
  Set objRSDetail = objConn.Execute(strSQL)
  strCOD_PROD = objRSDetail("LAST_PROD")
  FechaRecordSet objRSDetail
  If strCOD_PROD&"" = "" Then
    strCOD_PROD = 0
  End If
  strCOD_PROD = strCOD_PROD + 1
  
  strSQL = "INSERT INTO TBL_PRODUTOS (COD_PROD, COD_EVENTO, GRUPO, TITULO, DESCRICAO, OBS, CAPACIDADE, OCUPACAO, DT_OCORRENCIA, DT_TERMINO, COD_PALESTRANTE, SYS_DT_INATIVO, NUM_COMPETIDOR_START, LOCAL, CARGA_HORARIA, LOJA_SHOW, LOJA_EDIT_QTDE, PALESTRANTE, CERTIFICADO_TEXTO, DIPLOMA_TEXTO, COD_PROD_VALIDA, EXTRA_INFO_SHOW, EXTRA_INFO_MSG, EXTRA_INFO_REQUERIDO, VOUCHER_TEXTO, CERTIFICADO_PDF, CONCURSO, REF_NUMERICA, GRUPO_INTL, TITULO_INTL, DESCRICAO_INTL, IMG, TITULO_MINI, CERTIFICADO_PDF_ORIENTACAO, VOUCHER_TEXTO_US, VOUCHER_TEXTO_ES, BGCOLOR, DINAMICA, SINOPSE, GRUPO_SUB, DIPLOMA_PDF, CUPOM_FISCAL) "
  strSQL = strSQL & "SELECT "&strCOD_PROD&", "&strCOD_EVENTO&", GRUPO, TITULO, DESCRICAO, OBS, CAPACIDADE, OCUPACAO, DT_OCORRENCIA, DT_TERMINO, COD_PALESTRANTE, SYS_DT_INATIVO, NUM_COMPETIDOR_START, LOCAL, CARGA_HORARIA, LOJA_SHOW, LOJA_EDIT_QTDE, PALESTRANTE, CERTIFICADO_TEXTO, DIPLOMA_TEXTO, COD_PROD_VALIDA, EXTRA_INFO_SHOW, EXTRA_INFO_MSG, EXTRA_INFO_REQUERIDO, VOUCHER_TEXTO, CERTIFICADO_PDF, CONCURSO, REF_NUMERICA, GRUPO_INTL, TITULO_INTL, DESCRICAO_INTL, IMG, TITULO_MINI, CERTIFICADO_PDF_ORIENTACAO, VOUCHER_TEXTO_US, VOUCHER_TEXTO_ES, BGCOLOR, DINAMICA, SINOPSE, GRUPO_SUB, DIPLOMA_PDF, CUPOM_FISCAL FROM TBL_PRODUTOS WHERE COD_PROD = " & objRSProd("COD_PROD")
  objConn.Execute(strSQL)
  
  %>
  - Produto: <%=objRSProd("TITULO")%><br>
  <%
  
  objRSProd.MoveNext
Loop
FechaRecordSet objRSProd
%>
<br>
<%
'Forma de pagamento

strSQL = "insert into tbl_evento_formapgto (COD_EVENTO, COD_FORMAPGTO, COD_PAIS, ID_LOJA, CEDENTE, CARTEIRA, AGENCIA, CONTA, GERENTE, CNPJ, RAZAO_SOCIAL, PARCELAS, INSTRUCOES, VALOR_MIN, VALOR_MAX, COD_CONTRATO, EXIBIR_LOJA, DT_LIMITE_VCTO, DV_AGENCIA, DV_CONTA, ASSINATURA, COD_MOEDA_COBRANCA, ARIEL, ARIEL_ASSUNTO, ARIEL_INTL, ARIEL_INTL_ASSUNTO, VALOR_TAXA, CABECALHO, RODAPE, NUM_DIAS_VCTO, TIPO, CAPTURA, PARCELA_VLR_MINIMO)"
strSQL = strSQL & " SELECT "&strCOD_EVENTO&", COD_FORMAPGTO, COD_PAIS, ID_LOJA, CEDENTE, CARTEIRA, AGENCIA, CONTA, GERENTE, CNPJ, RAZAO_SOCIAL, PARCELAS, INSTRUCOES, VALOR_MIN, VALOR_MAX, COD_CONTRATO, EXIBIR_LOJA, DT_LIMITE_VCTO, DV_AGENCIA, DV_CONTA, ASSINATURA, COD_MOEDA_COBRANCA, ARIEL, ARIEL_ASSUNTO, ARIEL_INTL, ARIEL_INTL_ASSUNTO, VALOR_TAXA, CABECALHO, RODAPE, NUM_DIAS_VCTO, TIPO, CAPTURA, PARCELA_VLR_MINIMO FROM tbl_evento_formapgto where cod_evento = " & strCOD_EVENTO_ORIGEM
objConn.Execute(strSQL)

%>
- Forma(s) de Pagamento(s)<br>
<br>
<%
Dim objRSMapeamento

strSQL = "SELECT * FROM TBL_MAPEAMENTO_CAMPO WHERE COD_EVENTO = " & strCOD_EVENTO_ORIGEM
Set objRSMapeamento = objConn.Execute(strSQL)
Do While not objRSMapeamento.EOF 
  
  
  strSQL = "INSERT INTO TBL_MAPEAMENTO_CAMPO (NOME_CAMPO_CLIENTE, NOME_CAMPO_PROEVENTO, NOME_DESCRITIVO, COD_EVENTO, LOJA_SHOW, CAMPO_COMBOLIST, CAMPO_REQUERIDO, CAMPO_COR_DESTAQUE, CAMPO_TIPO, TIPO, NOME_DESCRITIVO_US, NOME_DESCRITIVO_ES, VINCULADO_ENTIDADE) "
  strSQL = strSQL & "SELECT NOME_CAMPO_CLIENTE, NOME_CAMPO_PROEVENTO, NOME_DESCRITIVO, "&strCOD_EVENTO&", LOJA_SHOW, CAMPO_COMBOLIST, CAMPO_REQUERIDO, CAMPO_COR_DESTAQUE, CAMPO_TIPO, TIPO, NOME_DESCRITIVO_US, NOME_DESCRITIVO_ES, VINCULADO_ENTIDADE FROM TBL_MAPEAMENTO_CAMPO WHERE COD_MAPEAMENTO_CAMPO = " & objRSMapeamento("COD_MAPEAMENTO_CAMPO")
  objConn.Execute(strSQL)
  
  %>
  - Campo Mapeado: <%=objRSMapeamento("NOME_CAMPO_CLIENTE") & " - " & objRSMapeamento("NOME_CAMPO_PROEVENTO")%><br>
  <%
  
  objRSMapeamento.MoveNext
Loop
FechaRecordSet objRSMapeamento
%>
<br>
<%
	
 Dim FSO, strPATH, strARQUIVO_ORIGEM, strARQUIVO
 Dim strCREDENCIAL_MODELO, strCREDENCIAL
 
 strPATH = Server.MapPath("../") & "\_database\"
' Response.Write(strPATH & "<BR>")
 
 Set FSO = createObject("scripting.filesystemobject") 
 
 strARQUIVO_ORIGEM = strPATH & "modelo_credencial" & "_" & strCOD_EVENTO_ORIGEM & ".asp"
 If FSO.FileExists(strARQUIVO_ORIGEM) Then
   strARQUIVO = strPATH & "modelo_credencial" & "_" & strCOD_EVENTO & ".asp"
    FSO.CopyFile strARQUIVO_ORIGEM, strARQUIVO
	%>
    - Credencial Modelo: <%=strARQUIVO%><br>
    <%
 End If
 
 Set FSO = Nothing
	 	 

%>
  <Br>
  <input type="button" onClick="document.location='copia_evento.asp?cod_evento_origem=<%=strCOD_EVENTO_ORIGEM%>'" name="btInicio" value="Voltar">
  </td>
 </tr>
</table>
<%
Else
%>
<table width="100%" border="0" cellpadding="2" cellspacing="0">
<form name="formcopiar" action="copia_evento.asp" method="post">
 <input type="hidden" name="acao" value="copiar">
 <tr>
  <td width="14%" align="right">Evento Origem:</td>
  <td width="86%">
  <select name="cod_evento_origem" class="textbox380" onChange="document.location='copia_evento.asp?cod_evento_origem='+this.value;">
  <%
  strSQL = "SELECT COD_EVENTO, NOME FROM TBL_EVENTO ORDER BY DT_INICIO DESC"
  MontaCombo strSQL, "COD_EVENTO", "NOME", strCOD_EVENTO_ORIGEM
  %>
  </select>
  </td>
 </tr>
 <tr>
  <td width="14%" align="right">Novo C&oacute;digo:</td>
  <td width="86%">
  <input type="text" name="cod_evento" value="<%=strCOD_EVENTO%>">
  </td>
 </tr>
 <tr>
   <td align="right">Novo T&iacute;tulo:</td>
   <td><input type="text" name="titulo" value="" class="textbox380"></td>
 </tr>
 <tr>
   <td>&nbsp;</td>
   <td><input type="submit" name="btEnviar" value="Copiar"></td>
 </tr>
</form>
</table>
<%
End If
%>
</body>
</html>
<%
FechaDBConn ObjConn
%>