    <!-- meta charset="utf-8" //-->
    <meta charset="iso-8859-1">
    <meta name="viewport"    content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="product"     content="pVISTA metro">

    <link href="_metroUI/css/metro-bootstrap.css"		 rel="stylesheet">
    <link href="_metroUI/css/metro-bootstrap-responsive.css"  rel="stylesheet">
    <link href="_metroUI/css/docs.css"			      rel="stylesheet">
    <link href="_metroUI/css/iconFont.css"      	   	  rel="stylesheet">
    <link href="_metroUI/js/prettify/prettify.css"	  rel="stylesheet">
    <link href="_metroUI/css/tablesort_metro.css" 	  rel="stylesheet">

    <!-- Load JavaScript Libraries -->
    <script src="_metroUI/js/jquery/jquery.min.js"></script>
    <script src="_metroUI/js/jquery/jquery.widget.min.js"></script>
    <script src="_metroUI/js/jquery/jquery.mousewheel.js"></script>
    <script src="_metroUI/js/jquery/jquery.easing.1.3.min.js"></script>
    <script src="_metroUI/js/holder/holder.js"></script>
    <script src="_metroUI/js/prettify/prettify.js"></script>
     <script src="_metroUI/js/start-screen.js"></script>
	 
    <!-- Local JavaScript -->
    <script src="_metroUI/js/load-metro.js"></script>
    <!-- Local JavaScript -->
    <script src="_metroUI/js/docs.js"></script>
    <script src="_metroUI/js/github.info.js"></script>

    <!-- Tablet Sort -->
    <script src="_metroUI/js/tablesort_metro.js"></script>
