<%
 HTMLAttribForm       = ""
 HTMLUpdateFieldFails = "Não foi possível atualizar o campo"
 HTMLOLEError         = "Tipo Incorreto"
 HTMLStatusStart      = "<TABLE><TR><TD><IMG SRC=""appWarning.gif"" ALT=""Aviso"" border=0></td><TD>&nbsp;</td><TD><SPAN CLASS=Warning>"
 HTMLStatusEnd        = "</SPAN></td></tr></table>"
 HTMLAutoIncrement    = "(Auto)"
 HTMLNotFound         = "Registro Não encontrado"
 HTMLStatusFieldError = "Não foi possível atualizar o campo "
 HTMLAttribSaveBtn    = "TYPE=""Submit"" Value=""Salvar"" CLASS=""Submit"""
 HTMLAttribCancelBtn  = "TYPE=""Submit"" Value=""Cancelar"" CLASS=""Submit"""
 HTMLAttribNewBtn     = "TYPE=""Submit"" Value=""Novo"" CLASS=""Submit"""
 HTMLAttribDeleteBtn  = "TYPE=""Submit"" Value=""Deletar"" CLASS=""Submit"""
 HTMLCheckField       = "<SPAN CLASS=Warning> Check Field </SPAN>"
%>
