	<%
	HTMLExportStart = "<html><head><title>1 Click DB Export</title></head>"
	HTMLExportEnd = "</body></html>"
	HTMLSearchKeyword = "<span class=""FieldName"">Palavra Chave: </span>"
	HTMLAttribGridEven = "class=""GridEven"""
	HTMLAttribGridOdd = "class=""GridOdd"""
	HTMLAttribBtnMultiDelete = "type=""submit"" class=""submit"" value=""Deletar"""
	HTMLAttribBtnMultiSelect = "type=""submit"" class=""submit"" value=""Select"""
	HTMLTextCompare = "=Exact Match|Exato;;Starts With|Começa com;;Contains|Contém;;Like|Como;;In|Em;;Is Null|É Nulo"
	HTMLGridButtons = "First|Primeiro;;Prev|Anterior;;paging|smbutton;;Next|Próximo;;Last|Último;;New|Novo;;Search|Busca;;DrillDown|Pesquisa por Campos;;Reset|Restaurar;;Print|Imprimir;;Excel"
	HTMLTrueValue = ""
	HTMLFalseValue = ""
	HTMLAttribFindBtn = "type=""submit"" value=""Busca"" class=""submit"""
	HTMLAttribCancelBtn = "type=""submit"" value=""Cancelar"" class=""Submit"""
	HTMLSearchBetween = "ENTRE"
	HTMLSearchBetweenAnd = "E"
	HTMLAttribGrid = ""
	HTMLSearchAll = "Buscar Todos "
	HTMLSearchAny = "Buscar Qualquer um "
	HTMLSearchAnd = " E "
	HTMLSearchOr = " OU "
	HTMLMemoContinues = " <span class=""Notice"">Continua...</span>"

	HTMLBinaryValue = "<span class=""Information"">Dados Binários</span>"
	HTMLNullValue = "&nbsp;"
	HTMLEditLink = "Editar"
	HTMLDetailLink = "Detalhes"
	HTMLSearchReSet = "Reset"
	HTMLDeleteLink = ""
	HTMLEditLink = "Editar"
	HTMLAscText = "menor Para maior"
	HTMLDescText = "maior Para menor"
	HTMLSortASCLink = "<small>A-Z"
	HTMLSortDESCLink = "<small>Z-A</small>"
	HTMLFilterLink = "<small>fltr</small>"

%>
